config/routes.rb
Rails.application.routes.draw do
  resources :badges
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register'}
   
  root to: 'pages#dashboard'

  get 'trophy', to: 'pages#trophy'

  get 'pages/points'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
	belongs_to :user, optional: true

	validates_presence_of :name, :description
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :has_merit, optional: true
  has_many   :badges

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  	@badges = Badge.all
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :description, :image, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
  	@badge = Badge.all
  end

  def trophy
  end

  def points
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/badges/_form.html.erb
<%= form_for(badge) do |f| %>
  <% if badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :badge_Id %><br />
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Badges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.name %></td>
        <td><%= badge.description %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BadgeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Users Name</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Dashboard", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Points", pages_points_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Trophy", trophy_path, class: "nav-link" %>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </form>
      </div>
    </nav>

    <%= yield %>

    <%= growlyflash_static_notices %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag "griffindor1.gif", class: "third-slide" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Houses you can belong to!</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "ravenclaw1.gif", class: "third-slide" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Another Houses you can belong to!</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "hufflepuff1.gif", class: "third-slide" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Another Houses you can belong to!</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "slytherin.gif", class: "third-slide" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Another Houses you can belong to!</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag "blog_badge.gif", class: "rounded-circle", width: 140, height: 140 %>
      <h2>Featured Badge</h2>
      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
      <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <%= image_tag "crown.gif", class: "rounded-circle", width: 140, height: 140 %>
      <h2>Featured Badge</h2>
      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
      <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <%= image_tag "guitar.gif", class: "rounded-circle", width: 140, height: 140 %>
      <h2>Featured Badge</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->


  <!-- FOOTER -->
  <footer>
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2017 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

</div><!-- /.container -->

app/views/pages/points.html.erb
<div class='container'>
<h1>Points</h1>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>
          #
        </th>
        <th>
          User Name
        </th>
        <th>
          User Email
        </th>
        <th>
          User Level
        </th>
        <th>
          Bages Earned(%)
        </th>
        <th>

        </th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  </table>
</div>

app/views/pages/trophy.html.erb
      <div class="background"></div>
      <div class="body_color">
                <h1 class="tropies-header">TROPHIES</h1>
            <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "blog_badge.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Label</h4>
              <div class="label">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
             <%= image_tag "crown.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Label</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "thumbs_up.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Label</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "guitar.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Label</h4>
              <span class="label">Something else</span>
            </div>
          </section>
      </div>
    </div>
    <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
             <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <div class="label">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
          </section>
      </div>
    </div>

    <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <div class="label">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
             <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
          </section>
      </div>
    </div>

    <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <div class="label">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
          </section>
      </div>
    </div>

    <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <div class="label">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
          </section>
      </div>
    </div>

    <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <div class="label">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <%= image_tag "badge-privacy-large.gif", class: "img-fluid rounded-circle", width: 200, height: 200 %>
              <h4 class="label">Locked</h4>
              <span class="label">Something else</span>
            </div>
          </section>
      </div>
    </div>
</div>